In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_lfw_people
import plotly.graph_objects as go
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler, StandardScaler, Normalizer, Binarizer, RobustScaler, label_binarize
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, PowerTransformer
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.tree import DecisionTreeClassifier, export_text, DecisionTreeRegressor
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, auc
from sklearn.metrics import make_scorer, mean_absolute_error, mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore')

In [4]:
# Load the data
faces = fetch_lfw_people(min_faces_per_person=60)


In [11]:
seed = 12345
X_train, X_test, y_train, y_test = train_test_split(faces.data, faces.target, random_state=seed, test_size=0.2)

red1 = MLPClassifier(random_state=seed, alpha=0.1, hidden_layer_sizes=(100,100), max_iter=1000, solver='adam', activation='relu')

In [12]:
red1.fit(X_train, y_train)

MLPClassifier(alpha=0.1, hidden_layer_sizes=(100, 100), max_iter=1000,
              random_state=12345)

In [13]:
y_pred = red1.predict(X_test)

In [14]:
# Mostrar la matriz de confusión
matriz_confusion = confusion_matrix(y_test, y_pred)
print("Matriz de confusión:")
print(matriz_confusion)

Matriz de confusión:
[[  5   3   3   0   1   0   0   0]
 [  0  43   3   0   0   0   0   2]
 [  0   4  15   2   0   0   0   0]
 [  0   9   7 100   2   0   1   3]
 [  0   1   1   3  17   1   0   1]
 [  0   2   0   0   0  12   0   2]
 [  0   1   0   0   0   1   6   0]
 [  0   2   1   0   1   0   0  15]]


In [15]:
precision = accuracy_score(y_test, y_pred)
y_pred_tr = red1.predict(X_train)
# Calcular la precisión del modelo
precision_tr = accuracy_score(y_train, y_pred_tr)
print(f"Precisión del modelo en train: {precision_tr:.4f}")
print(f"Precisión del modelo en test: {precision:.4f}")

Precisión del modelo en train: 0.9805
Precisión del modelo en test: 0.7889
